name: gradd
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # ── core functionality ────────────────────────────────────────────
  parse_server_sdk_flutter: ^8.0.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # ── UI / state ────────────────────────────────────────────────────
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  animated_bottom_navigation_bar: ^1.3.2
  provider: ^6.1.2
  intl: ^0.18.1
  image_picker: ^1.1.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # generates the launcher icons from assets/images/app_icon.png
  flutter_launcher_icons: ^0.13.1

# ─────────────────────────────────────────────────────────────────────
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png      # logo (also used as launcher icon)
